spring.application.name=backend
server.port=8080


spring.security.oauth2.client.registration.google.client-id=284981586957-o7auikm6re6nh1lutroljf04mpbsdvd9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.admin-emails=${ADMIN_EMAILS:}
# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://admin:123@cluster0.mitomzn.mongodb.net/Campus_Management
spring.mongodb.uri=mongodb+srv://admin:123@cluster0.mitomzn.mongodb.net/Campus_Management

# Logging configuration
logging.level.root=INFO
logging.level.com.smartcampus=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.security=DEBUG

# MongoDB timeout configuration
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.delay-between-checking-pool-size=10000

# Module A image upload (Option B: local file server)
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
