spring.application.name=backend
# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://admin:123@cluster0.mitomzn.mongodb.net/Campus_Management
spring.mongodb.uri=mongodb+srv://admin:123@cluster0.mitomzn.mongodb.net/Campus_Management

# Logging configuration
logging.level.root=INFO
logging.level.com.smartcampus=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.security=DEBUG

# MongoDB timeout configuration
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.delay-between-checking-pool-size=10000

# Module A image upload (Option B: local file server)
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
